### ISSUE TITLE
Please add the docker-compose.yml 

### ISSUE THREAD

**Issue by grunya404** [OnApp/cloudnet#2]
here are the documentation http://docs.docker.com/compose/rails/
in addition, as well as question:
I'm not a fan of rails, and would like to work independently with the API Cloud.net and other modules of the CP. 
Where I can  find documentation about the API Cloud.net? or a description of what is the structure this control panel (how it works)?

thanks

**Comment by tombh** [comment]
I just haven't been convinced by any docker postgres images yet. Default config seems to be insecure and managing persistent volumes in docker is not straightforward. Unless there is a specific use case I think it is best for now to just use native Postgres installation.

We don't have an API for Cloud.net at the moment. Although it is certainly something we are considering for future versions.

**Comment by suhailpatel** [comment]
One thing to note is that Cloud.net talks directly to the OnApp Control Panel to manage all the Virtual Machine management. You can find the documentation for the OnApp API here: https://docs.onapp.com/display/35API

**Comment by grunya404** [comment]
Thank you.
