### ISSUE TITLE
Docker and postgres

### ISSUE THREAD

**Issue by ebsalberto** [OnApp/cloudnet#4]
Hello,

I'm following the README to install Jager locally but when I run 

```
docker run --env-file=.env --rm cloudnet rake db:create
```

I get an error about the db not being able to be created - https://gist.github.com/ebsalberto/6e0e0669d62bda439414

What am I missing?

Thank you.

**Comment by tombh** [comment]
Hiya, you just need to populate the `DB_*` fields in your `.env` file. For example, `DB_HOST=192.168.1.1`, etc

**Comment by ebsalberto** [comment]
Hey Tom, so do I need to run another container with psql and link them together? Thanks

**Comment by tombh** [comment]
That's completely up to you. Personally I try to avoid running DBs in Docker as much as possible. If you're on debian/ubuntu, then `apt-get install postgresql redis` and make sure `pg_hba.conf` and `postgres.conf` accept non-local connections.
